# This file contains sensitive information (passwords/secrets) and should NOT be checked in to version control.
# It is safe to keep this in .gitignore - see the root .gitignore for the pattern.

[repo]
password = "a very secret password"

[repo.envs]
ACCOUNT_ID="id"
ACCOUNT_KEY="account_key"