[repo]
name = "Example"
restic_repo_url = "b2:example-restic-backups:example-system"
restic_bin = "restic"

[repo.paths]
log_folder = "./logs/"
include_patterns = [
    "/home/user/",
    "/etc/var/www/",
    "/home/user/very-important/"
]
exclude_patterns = [
    # folders
    "site-packages",
    "node_modules",
    ".git",
    ".idea",
    "javaEclipse",
    "AppData",
    "nvm",
    # python environments
    "*-env",
    "__pycache__",
    # file types
    "*.pyc",
    "*.exe",
    "*.ISO",
    "*.iso"
]

[repo.post_backup]
forget = true
forget_dry = true
check = true
shutdown = false